[[redirects]]
	from = "https://playerdash.id"
	to = "https://playerdash.id/de"
	status = 302
	conditions = {Language = ["de"]}

[[redirects]]
	from = "https://playerdash.id/de"
	to = "https://playerdash.id"
	status = 302
	conditions = {Language = ["en"]}
