[[redirects]]
	from = "/*"
	to = "/de"
	status = 302
	force = true
	conditions = {Language = ["de"]}

[[redirects]]
	from = "/de/*"
	to = "https://playerdash.id"
	status = 302
	force = true
	conditions = {Language = ["en"]}